sudo: true

os:
- linux

addons:
  apt:
    packages:
    - debootstrap
    - dchroot
    - apt
    - dpkg
    - dpkg-dev
    - debianutils
    - debconf
    - binutils
    - fakeroot

before_script:
- sudo -E apt-get -y update
- export CHROOTDIR=$TRAVIS_BUILD_DIR/chroot
- sudo -E mkdir -p $CHROOTDIR
- chmod a+x $TRAVIS_BUILD_DIR/setup.sh && sudo -E $TRAVIS_BUILD_DIR/setup.sh

script:
- cd $CHROOTDIR
- sudo -E chmod a+x build/scripts/build.sh
- sudo -E chroot $CHROOTDIR build/scripts/build.sh

after_success:
- sudo -E cp $CHROOTDIR/build/alpine-rpi-3.7.0-aarch64-4.16-*.tar.xz $TRAVIS_BUILD_DIR/
- sudo -E chmod a+rw $TRAVIS_BUILD_DIR/alpine-rpi-3.7.0-aarch64-4.16-*.tar.xz
- |
  sudo -E umount -l $CHROOTDIR/dev/pts
  sudo -E umount -l $CHROOTDIR/dev
  sudo -E umount -l $CHROOTDIR/sys
  sudo -E umount -l $CHROOTDIR/proc
- cd $TRAVIS_BUILD_DIR && sudo -E rm -rf $CHROOTDIR

cache:
  apt: true

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/alpine-rpi-3.7.0-aarch64-4.16-*.tar.xz
  on:
    tags: true

env:
  global:
    secure: H7zpAEum3F8g3I4IVGKI45TfhQsnZNABJPsfsm9KZjuOdlpzuwalT74RWc55n1P7sCKvOy0ZvliN6ZGW7uRZSbVnFhpxpmUiV9B9fEUaS1VVYnGpgcYPCWSiG3DvKedsxGroHF8mzEbmrW4AMkuFcg64xDg6r5GnbRxtDmr78iKntx9Zc0CBDIaN3LotXgp5B6/K35db+mJ/dwtpGMw9sHNGvdYDtAxZko3Wc6dYxVQfy8jf6+SnuWk2Ua4LAkDA0gomihPBYQwEvYgR3l9YlRfYU6lnq390BFxRcNl2LfXMcTd48AqPF14Qs+AtgJBi0KrPZBYwJC115kVZVYhjCWWNvV2PynjHbxHaeMkC3eEMf1MjKTJzrLxPkvFtbLmJvD2iGSJ58PvQgjgpAqjbhC+m6Ck8y56mbFdrHjHDKv1q0bnUgz9jR7CUX3L4Ghm6zpJa9MkJFaLe8VwJKdC0Bk3oqkMAhqwk/eYmNK5AZTAcmYJ6pg56oF9MmjOwZgGwkoFATvbU0rHqjN2nPFKG9pmKHPRNSa102P4Z6XRX6/MRQ/Iz4Ca4IXP/8QY/MVu15ubsklz6Vcf/t+rwUCV63KN6dygdryA6TARKptMY0VukquEjOQpMhPDCDraS6X+Hl04Itbvjtho9zbIo3LUwCHEHWVWBXwo9kVcLrML+eAw=
